# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fcc1936a9ea90e64c2ad414fb6e029c602082f9bc5759c748899d217c2d4036283e47552c7f5329910cd315e7d3ea93f06dcd158477044f9edca729acb558a

test:
  secret_key_base: 19d16c8481bee662f8f526960faf4673a5db9668bad9792e186cc68f6f0649c2c487ac61d456aa412a4c03acb8b509136bc8e5d65e89fa1e232d0dd54787e1ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
